name:                secd-lambda-calculus
version:             0.1.0.0
github:              "Blaisorblade/secd-lambda-calculus"
license:             BSD3
author:              "Paolo G. Giarrusso"
maintainer:          "p.giarrusso@gmail.com"
copyright:           "Copyright (c) 2021 Paolo G. Giarrusso"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Blaisorblade/secd-lambda-calculus#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  secd-lambda-calculus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secd-lambda-calculus

tests:
  secd-lambda-calculus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secd-lambda-calculus
